Models/Wedding.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace WeddingPlanner.Models
{
    public class Wedding
    {
        [Key]
        public int WeddingId { get;set;}
        [Required]
        [Display(Name ="Wedder One: ")]
        public string WedderOne { get;set;}
        [Required]
        [Display(Name = "Wedder Two: ")]
        public string WedderTwo{get;set;}
        [Required]
        [FutureDate]
        public DateTime Date{get;set;}
        [Required]
        public string Address {get;set;}
        public int UserId { get;set; }
        public User Planner {get;set;}
        public List<Rsvp> GuestList {get;set;}
        public DateTime CreatedAt {get;set;}
        public DateTime UpdatedAt{get;set;}

    }

    public class FutureDateAttribute : ValidationAttribute
    {
        protected override ValidationResult IsValid (object value, ValidationContext validationContext)
        {
            DateTime date;
            if(value is DateTime)
            {
                date = (DateTime)value;
            }
            else
            {
                return new ValidationResult("Invalid DateTime");
            }
            if( date < DateTime.Now)
            {
                return new ValidationResult("Date must be in the future!");
            }
            return ValidationResult.Success;
        }
    }
}

Controllers/WeddingController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WeddingPlanner.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace WeddingPlanner.Controllers
{
    [Route("weddings")]
    public class WeddingController : Controller
    {
         private HomeContext dbContext;
        public WeddingController(HomeContext context)
        {
            dbContext =  context;
        }

        [HttpGet("")]
        public IActionResult Dashboard()
        {
            if(HttpContext.Session.GetString("UserEmail") == null)
            {
                return RedirectToAction("LogOut", "Home");
            }
            else
            {
                User userInDb = dbContext.Users.Include(u => u.PlannedWeddings ).FirstOrDefault( u =>  u.Email == HttpContext.Session.GetString("UserEmail"));
                ViewBag.User = userInDb;

                List<Wedding> AllWeddings = dbContext.Weddings.Include(w => w.GuestList ).ThenInclude(r => r.Guest).ToList();
                return View(AllWeddings);
            }
        }

        [HttpGet("new")]
        public IActionResult New()
        {
            if(HttpContext.Session.GetString("UserEmail") == null)
            {
                return RedirectToAction("LogOut", "Home");
            }
            else
            {
                User userInDb = dbContext.Users.Include(u => u.PlannedWeddings ).FirstOrDefault( u =>  u.Email == HttpContext.Session.GetString("UserEmail"));
                ViewBag.User = userInDb;


                return View();
            }

        }

        [HttpPost("create")]
        public IActionResult Create(Wedding plan)
        {
             if(HttpContext.Session.GetString("UserEmail") == null)
            {
                return RedirectToAction("LogOut", "Home");
            }
            else
            {
                if(ModelState.IsValid)
                {
                    dbContext.Weddings.Add(plan);
                    dbContext.SaveChanges();
                    return Redirect($"show/{plan.WeddingId}");
                }
                else
                {
                    User userInDb = dbContext.Users.Include(u => u.PlannedWeddings ).FirstOrDefault( u =>  u.Email == HttpContext.Session.GetString("UserEmail"));
                    ViewBag.User = userInDb;
                    return View("New");
                }
            }

        }

        [HttpGet("show/{weddingId}")]
        public IActionResult Show(int weddingId)
        {
            if(HttpContext.Session.GetString("UserEmail") == null)
            {
                return RedirectToAction("LogOut", "Home");
            }
            else
            {
                User userInDb = dbContext.Users.Include(u => u.PlannedWeddings ).FirstOrDefault( u =>  u.Email == HttpContext.Session.GetString("UserEmail"));
                ViewBag.User = userInDb;
                Wedding flapjack = dbContext.Weddings.Include(w => w.GuestList).ThenInclude(r => r.Guest).Include(w => w.Planner).FirstOrDefault(w => w.WeddingId == weddingId);

                return View(flapjack);
            }

        }

        [HttpGet("destroy/{weddingId}")]
        public IActionResult Destroy(int weddingId)
        {
            if(HttpContext.Session.GetString("UserEmail") == null)
            {
                return RedirectToAction("LogOut", "Home");
            }
            else
            {
                Wedding remove = dbContext.Weddings.FirstOrDefault(w => w.WeddingId == weddingId);
                dbContext.Weddings.Remove(remove);
                dbContext.SaveChanges();
                return RedirectToAction("Dashboard");
            }

        }

        [HttpGet("rsvp/{weddingId}/{userId}/{status}")]
        public IActionResult RSVP(int weddingId, int userId, string status)
        {
            if(HttpContext.Session.GetString("UserEmail") == null)
            {
                return RedirectToAction("LogOut", "Home");
            }
            else{

            
                if(status == "add")
                {
                    Rsvp response = new Rsvp();
                    response.UserId = userId;
                    response.WeddingId = weddingId;
                    dbContext.Rsvps.Add(response);
                    dbContext.SaveChanges();

                }
                if(status == "remove")
                {
                    Rsvp remove = dbContext.Rsvps.FirstOrDefault(r => r.WeddingId == weddingId && r.UserId==userId);
                    dbContext.Rsvps.Remove(remove);
                    dbContext.SaveChanges();
                }
                return RedirectToAction("Dashboard");
            }

        }

        
    }
}

Views/Wedding/Dashboard.cshtml
@model List<Wedding>

<h1>Welcome @ViewBag.User.FirstName!</h1>

<a asp-action="Logout" asp-controller="Home" class="btn btn-danger">Logout</a>

<table class="table table-hover">
    <thead>
        <tr>
            <th>Wedding</th>
            <th>Date</th>
            <th>Guests</th>
            <th>Action</th>
        </tr>

    </thead>
    <tbody>
        @foreach( var w in @Model)
        {
            <tr>
                <td><a asp-action="Show" asp-controller="Wedding" asp-route-weddingId="@w.WeddingId">@w.WedderOne & @w.WedderTwo</a></td>
                <td>@w.Date.ToString("d")</td>
                <td>@w.GuestList.Count</td>
                @if(@ViewBag.User.UserId == @w.UserId)
                {
                    <td><a asp-action="Destroy" asp-controller="Wedding" asp-route-WeddingId="@w.WeddingId">DELETE</a></td>
                }
                else
                {
                    @if(w.GuestList.All(r => r.UserId != @ViewBag.User.UserId))
                    {
                        <td><a asp-action="RSVP" asp-controller="Wedding" asp-route-weddingId="@w.WeddingId" asp-route-userId="@ViewBag.User.UserId" asp-route-status="add">RSVP</a></td>
                    }
                    @if(w.GuestList.Any(r => r.UserId == @ViewBag.User.UserId))
                    {
                        <td><a asp-action="RSVP" asp-controller="Wedding" asp-route-weddingId="@w.WeddingId" asp-route-userId="@ViewBag.User.UserId" asp-route-status="remove">Un-RSVP</a></td>
                    }
                }
                
            </tr>
        }
    </tbody>
</table>

<a asp-action="New" asp-controller="Wedding">Create Wedding</a>

Views/Wedding/New.cshtml
@model Wedding

<h1>Plan your wedding</h1>

<div asp-validation-summary="All" class="text-danger"></div>

<form asp-action="Create" asp-controller="Wedding" method="post">
    <label asp-for="WedderOne"></label>
    <input asp-for="WedderOne"><br>
    <label asp-for="WedderTwo"></label>
    <input asp-for="WedderTwo"><br>
    <label asp-for="Date"></label>
    <input type="date" asp-for="Date"><br>
    <label asp-for="Address"></label>
    <input asp-for="Address"><br>
    <input type="hidden" asp-for="UserId" value="@ViewBag.User.UserId">
    <input type="submit" value="Plan It" class="btn btn-outline-warning">


</form>

Views/Wedding/Show.cshtml
@model Wedding

<h1>@Model.WedderOne & @Model.WedderTwo's Wedding</h1>
<a asp-action="Dashboard" asp-controller="Wedding" class="btn btn-warning">Dashboard</a>
<a asp-action="Logout" asp-controller="Home" class="btn btn-danger"></a>

<h2>When: @Model.Date.ToString("MMMM dd, yyyy")</h2>
<h2>Where: @Model.Address</h2>

<div>
    <h6>Guest List:</h6>
    @if(@Model.GuestList.Count == 0)
    {
        <p>Nobody loves us!</p>
    }
    @foreach(var r in @Model.GuestList)
    {
        <p>@r.Guest.FirstName @r.Guest.LastName</p>
    }
</div>